version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile

    container_name: deliverygofront
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./front
        target: /front
    networks:
      - deliverygonetwork
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    container_name: deliverygoback
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./back
        target: /back
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - deliverygonetwork
    environment:
      - MONGO_URL=mongo
      - PORT:8080
    env_file:
      - ./back/.env
  mongo:
    image: mongo
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    networks:
      - deliverygonetwork
    restart: always
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - deliverygonetwork
networks:
  deliverygonetwork:
    driver: bridge
