name: Merge Bugfixess to Master

on:
  push:
    branches:
      - bugfixes

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge bugfixes into master
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          git checkout master
          git merge --no-ff ${{ github.ref }}
          
          git push origin master
