name: Full-stack CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for React
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install React dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Set up Node.js for Express.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Express.js dependencies
        run: npm install

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          # Build and push React Docker image
          docker build -t my-react-app -f front/Dockerfile .
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker tag my-react-app $DOCKERHUB_USERNAME/my-react-app:latest
          docker push $DOCKERHUB_USERNAME/my-react-app:latest

          # Build and push Express.js Docker image
          docker build -t my-express-app -f back/Dockerfile .
          docker tag my-express-app $DOCKERHUB_USERNAME/my-express-app:latest
          docker push $DOCKERHUB_USERNAME/my-express-app:latest
