name: Merge Bugfixes to Production

on:
  push:
    branches:
      - 'bugfixes'

jobs:
  merge-to-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge changes to production
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        
        # Replace 'production' with your target branch name
        TARGET_BRANCH="production"
        
        # Get the name of the branch pushed
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
        
        # Check if the branch is bugfixes/*
        if [[ $BRANCH_NAME == "bugfixes/"* ]]; then
          git checkout -b "${BRANCH_NAME}"
          git merge --no-ff "${BRANCH_NAME}" -m "Merge branch '${BRANCH_NAME}' into ${TARGET_BRANCH}"
          git push origin "${TARGET_BRANCH}"
        else
          echo "Branch is not bugfixes/*, no automatic merge will be performed."
        fi
