name: Hotfix Merge

on:
  push:
    branches:
      - hotfix-branch

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge hotfix into master
        run: |
          git fetch
          git checkout master || git checkout -b master
          git merge --no-ff ${{ github.event.before }}
          git push origin master
